### ISSUE TITLE
Reasons for keeping code-alliance (and Josra) related project under our Praqma organisation

### ISSUE THREAD

**Issue by buep** [Praqma/josra#11]
This issue is about two things:

* documenting why we own all the code-alliance project and have placed them on our github project (compared to putting them in a josra or code-alliance Github org.)
* suggesting a setup, where we can ensure that the repositories are owned by a community, not only Praqma (maybe forks?)

Here is an extract of the decision around why they should stay in the Praqma organisation (editied slightly for clarity):

L: 
> I’d like to create a “Praqma’s Code Alliance” organization where we could fork (or move???) all Josra/alliance repos to, that would allow us to invite alliance members.
> What’s special about the Alliance organization is that it woudl _always_ and _only_ have Public repos

B: 
> I don't like to move our existing repos... JOSRA org was empty for that purpose as well. I don't see any benefit from moving those repos out of our Praqma org to another Praqma maintained org for several reasons:
> * we need to maintain our own employee accounts in two orgs because ot of us need to be in the new code-alliance
> * all repos get new names... we need to update docs, url, links, build jobs, blog posts etc.... to some extend
> * we are the only one who actually contributes - beside from few pull requests now and then from real outsiders... none of our members ever contributed with code, so they don't need access to our repos...
> I really so not benefits of the exercise, but a lot of work and mess to clean-up

L: 
> Check! - I’ll buy that argument - _"non-praqma-contributores will have to contribute through pull requests”_ I rest my case
> As long as we can give the guarantee to all Alliance members that _”All Alliance repos are always public”_

B: 
> then all contributors, whether allicance-member or completely strangers will be contributing the same way... the well established same way all github orgs seem to use.

B: 
> > As long as we can give the guarantee to all Alliance members that _”All Alliance repos are always public”_
> Right, good and important point. Today they can't trust that, unless they trust us. We will look into ensuring that somehow

L: 
> “Benevolent Dicator Governance Model"

**Comment by lakruzz** [comment]
Hi @buep - do we need to do more on this one? We all agree - it's basically business as usual, so there's not much to document.

**Comment by lakruzz** [comment]
I actually added a §5 to our ground rules - that should cover it :-)
