### ISSUE TITLE
open up for new member in josra slack

### ISSUE THREAD

**Issue by buep** [Praqma/josra#13]

**Comment by lakruzz** [comment]
NO ONE besides praqma people are actually using josra.slack.com - should we revitalize it - or kill it?

btw - I've upped your privileges to _owner_ now you can do anything :-)

**Comment by buep** [comment]
I think we should ask about it Thurday... do they still want to keep it or should we just kill it?

**Comment by buep** [comment]
Not relevant any more - it was 5th gathering. Closing.
