### ISSUE TITLE
SoW on a bunch of Tracey features

### ISSUE THREAD

**Issue by lakruzz** [Praqma/josra#19]

**Comment by lakruzz** [comment]
@MadsBaggesen -  did you see that I assigned this one for you.

Can you draft - maybe in a google document that you can attach to this issue - the ideas you had for a Tracey feature upgrade for Siemens?

**Comment by MadsBaggesen** [comment]
@lakruzz Yes, I am aware.

I will coordinate with @martinmosegaard  and @RandomSort and put something together. Hopefully we will have a talk and first draft some use-cases ready before Christmas, but I will not commit to it as we are quite busy already.

**Comment by Andrey9kin** [comment]
@MadsBaggesen I know that @meekrosoft is considering working on visualization solution so please keep him and me in cc. Thanks!

**Comment by MadsBaggesen** [comment]
@RandomSort, @martinmosegaard and I had a short coordination session just before Christmas. The output was that the interests of Grundfos and Siemens are different, and we will treat it as two (or more) potential SoWs.

@RandomSort will play the ball for Grundfos regarding triggering using Tracey, will do input for an SoW, but expects the SoW to be done by @Andrey9kin .
@martinmosegaard will talk to Bert and Søren at Siemens and report back on what they want/would like/would use. This will take some time, and requires some internal discussion. Should maybe be handled in it's own issue.

I will assign this to Johan for now.

**Comment by lakruzz** [comment]
@martinmosegaard and @RandomSort what is the status on these SoWs?

Any progress since Jan 5th?

**Comment by martinmosegaard** [comment]
@lakruzz No progress on my side, but Siemens will be represented on 27th April

**Comment by buep** [comment]
Not relevant any more, closing.
