### ISSUE TITLE
Define praqma products (product owners and concept owners)

### ISSUE THREAD

**Issue by buep** [Praqma/josra#2]
I started this board: https://trello.com/b/SyoNNmDX/praqma-products

Idea was to define product and concept owners, architects etc. 

@sofusalbertsen that relates a bit to what you are doing right now with defining Praqma products.

I will still like the approach with product owners and concept owners... that is important for me. So maybe we should define those roles and have named roles on the products.
Idea with these is to better control product backlog and work.

**Comment by sofusalbertsen** [comment]
https://github.com/Praqma/josra/blob/master/tools.md

**Comment by buep** [comment]
Not relevant anymore... driving from the BD role project.
