### ISSUE TITLE
Retrospective 6

### ISSUE THREAD

**Issue by buep** [Praqma/josra#25]
Call, organize and follow up on retrospective from 6th gathering. 
Preferably make the online meeting Thursday or Friday morning next week so we can also evaluate on SoW getting out.

**Comment by JasmineCrozier** [comment]
@buep Sorry I kind of dropped the ball on that one. Things got a bit messy for me with Embedded Day in Oslo the next week, and the restructuring of the marketing team.
Thanks for planning the call!!
