### ISSUE TITLE
SoW for PiP pipeline compliant - we have to customers interested

### ISSUE THREAD

**Issue by buep** [Praqma/josra#28]
We need a statement of work on implementing the agreed feature from the workshop.

You can work in the relevant repositories or google drive on the writing, this issues is just tracking we make the SoW, get it to the customers, get approval, plan the work etc.

**Comment by MadsNielsen** [comment]
Right. I've split the SOW in two for now. 1 detailing the need to add pipeline compatibility, and another detailing the branch context switching. They're stored on our drive in the praqma.customers/CodeAlliance folder on drive. @buep and @bicschneider.

**Comment by buep** [comment]
I took the liberty to change the format a bit, matching our latest way of writing SoW. Have a look at this Praqma internal Gdoc: https://docs.google.com/document/d/1Dp5I69qlFEWuvjKcVUWRAxyH6tqLskVpSXd4dSqsPok/edit#

Changes are done to explain the problem better, suggest the solution and a few details of implementation.
Does the estimate still holds?

**Comment by buep** [comment]
Before editing the other, please decide if my version of the one Mads made is better.

**Comment by buep** [comment]
Regarding the branch context SoW I would like to see some concrete example on the renaming we deliver first. It think we agreed on only 2-3 in our meeting.

**Comment by buep** [comment]
@MadsNielsen - status please? 2 days since I gave some feedback on the SoW....

**Comment by MadsNielsen** [comment]
@buep Im okay with the new format. The only reason i choose the format was because i googled what a formal SOW should contain. I like the compact format you created avoiding bullets. Estimate should still hold. 

I've added the scenarios we talked about to the branch context SOW...which we can convert to the compact format if that is what we do.

**Comment by buep** [comment]
Great - can you make the context branch SoW a bit simpler?
 ...less bullets, make sure to formulate the problem so it is very clear what exact problem we try to solve.

Then I think they are ready.

**Comment by buep** [comment]
@MadsNielsen could you go over the branch context SoW and fit it to our new format?

**Comment by MadsNielsen** [comment]
@buep There you yo i edited the branch context SoW: https://docs.google.com/document/d/1Nrd4VZLgRR0INCkqgT7oZWMxZ74WYVMcF8IfalhnOwE/edit#

**Comment by buep** [comment]
Cool, I'll read it.

Any good inputs how we publish these sow now and in the future?

**Comment by buep** [comment]
Finished the SoW... find them here:

https://github.com/Praqma/pretested-integration-plugin/tree/master/docs/SoW
