### ISSUE TITLE
SoW Git Phlow - add Jira support - two customers interested

### ISSUE THREAD

**Issue by buep** [Praqma/josra#29]
We need a statement of work on implementing the agreed feature from the workshop.

You can work in the relevant repositories or google drive on the writing, this issues is just tracking we make the SoW, get it to the customers, get approval, plan the work etc.

**Comment by groenborg** [comment]
jira has its own workflow, so we need input from customers using Jira to figure out how we integrate the Jira workflow in the tool

**Comment by buep** [comment]
Conclusion on follow-up meeting today:

* Jan and Simon work out as many technical details as possible on Friday
* They make a kind of SoW as soon as possible
* They ping Lars and Bue which will continue from there.

**Comment by JKrag** [comment]
First draft of SOW at https://docs.google.com/a/praqma.net/document/d/1omYdz3kaSSAQn0NwoauDQmJq1qHBI8rs73BR8kmmyLs/edit?usp=sharing

**Comment by buep** [comment]
Feedback in the document...

**Comment by buep** [comment]
@groenborg and @JKrag  are you aware of https://www.npmjs.com/package/jira-git and how you think it ties together with git phlow etc. ?

**Comment by buep** [comment]
@groenborg @JKrag - I finished the SoW - please read through and comment also on the estimate Simon.

https://docs.google.com/document/d/1omYdz3kaSSAQn0NwoauDQmJq1qHBI8rs73BR8kmmyLs/edit#

**Comment by buep** [comment]
I got feedback from @JKrag  - thanks. I'll publish the Sow.

**Comment by buep** [comment]
closed with https://github.com/Praqma/git-phlow/commit/1deb88cf79f40c6e7a7cc7ff9b81b7c9461d6025

**Comment by JKrag** [comment]
Looks fine to me. I guess we can also close #100 now, as I see it as a duplicate of this one? Or is it left for the actual implementation of this SoW?
