### ISSUE TITLE
SoW Git Phlow - add good Windows support - two customers interested

### ISSUE THREAD

**Issue by buep** [Praqma/josra#30]
We need a statement of work on implementing the agreed feature from the workshop.

You can work in the relevant repositories or google drive on the writing, this issues is just tracking we make the SoW, get it to the customers, get approval, plan the work etc.

**Comment by groenborg** [comment]
We need support for windows and a way to distribute it. We need to consult customers to see if Chocolatey as package manager is a valid option. If customers wants a MSI we can look at that as well

**Comment by buep** [comment]
Conclusion on follow-up meeting today:

* Jan and Simon work out as many technical details as possible on Friday
* They make a kind of SoW as soon as possible
* They ping Lars and Bue which will continue from there.

**Comment by JKrag** [comment]
Draft for SoW can now be found at https://docs.google.com/a/praqma.net/document/d/1pXX0MvWDKHBvCDeWfMYZY4k0TxbUTSesy17x_RJOVpc/edit?usp=sharing 

@buep Can you have a quick look and give feedback?

**Comment by buep** [comment]
Edited the SoW... and few comments... go have a look and accept suggestions etc.

**Comment by buep** [comment]
@groenborg @JKrag - I finished the SoW - please read through and comment also on the estimate Simon.

https://docs.google.com/document/d/1pXX0MvWDKHBvCDeWfMYZY4k0TxbUTSesy17x_RJOVpc/edit

**Comment by buep** [comment]
closing this with this issue https://github.com/Praqma/git-phlow/issues/109
