### ISSUE TITLE
SoW 2Git - Add SVN support

### ISSUE THREAD

**Issue by JKrag** [Praqma/josra#36]
I could use a rough estimate for this for Napatech reasonably soon. 
I guess that means I will have to come up with a SoW for it unless the 2Git team has one already in progress?
@drBosse @praqma-thi

**Comment by drBosse** [comment]
@JKrag I think you would have to be more specific about the problem to solve to get an estimate

To start we need to investigate how we can include existing tools in 2git

**Comment by praqma-thi** [comment]
I'm also a bit hesitant about this. Adding SVN support could be flogging a thoroughly flogged dead horse. Incorporating an existing tool to do the bulk of the work is an option, but then I feel we might as well just add git2git support, right?

I'd love to hear about the usecase, though.

**Comment by buep** [comment]
Ping @drBosse @praqma-thi - issue is awaiting feedback... and shows up in filter as unread!

**Comment by sofusalbertsen** [comment]
@JKrag why not use the already working git-svn conversion tool that exists?
https://www.atlassian.com/git/tutorials/svn-to-git-prepping-your-team-migration

**Comment by praqma-thi** [comment]
As part of the issue Bosse referenced, I added a [roadmap entry for SVN support](https://github.com/Praqma/2git/blob/master/docs/roadmap/svn-support.md).

It's not particularly detailed, but it could be start of a SoW.

**Comment by praqma-thi** [comment]
Had a chat with @chopse, he mentioned a customer of his is also interested in 2git's SVN support, since their repositories have gone through unconventional changes over the years, causing standard migration tools to choke.

**Comment by drBosse** [comment]
@JKrag This is still open, are you not happy with the response?

**Comment by JKrag** [comment]
Thanks Bosse. I think Thierry's writeup is fine for what I need for now. Thanks for closing the issue.
