### ISSUE TITLE
SoW PAC - SVN support

### ISSUE THREAD

**Issue by JKrag** [Praqma/josra#37]
I could use a rough estimate for this for Napatech reasonably soon. 
I guess that means I will have to come up with a SoW for it unless we already have one lying around or in progress? 
@MadsNielsen ?

**Comment by buep** [comment]
Great!

Is it correct understood we need to talk to a SVN server to iterate over changesets? In that case should we test toward a specific server to start with?

**Comment by MadsNielsen** [comment]
In many ways...i think SVN should be simpler to implement than git. (Commits are numbered).

There are some svn ruby binding available:  https://github.com/dvwright/svn_wc 

In PAC all we'd really need is to implement the `get_delta(...)` method. And i assume they do not really branch at all, or use more or less permanent feature branches right? 

I'd echo the same estimate we came up during our brief chat on slack...i'd say roughly 40ish hrs (A week) including  unit tests.

**Comment by JKrag** [comment]
In the specific case, branches are very much used - especially long lived branches :-)
I assume that most SVN-projects big enough to consider 2Git instead of simple gitsvn conversion will be using branches heavily.

Branches are "just" folders, and should be reasonably easy to convert. All commits are numbered in a global incremental counter and can be traversed in that order. It should be easy to create and commit to branches as needed during the process. Even merges should doable - or so I believe at least.

**Comment by buep** [comment]
Isn't your last comment Jan ment for another issue? 2git? We don't commit anything in pac.

**Comment by JKrag** [comment]
@buep Yes, obviously it is about 2git :-( sorry. "Don't comment issues after midnight".
Just ignore the comment. 
I could also delete the comment and this one - is that better?

**Comment by buep** [comment]
@MadsNielsen can you create a briefing issue in PAC so we can discuss the SVN support.
The first comment there will be your short write-up on how would implement it if you were doing it.
If you already know which part of the code, without spending to much time on the details, it would be good to mention it.
Remember also to mention how we can test it....

Please link the issue here.

**Comment by buep** [comment]
We grooming the technical part in https://github.com/Praqma/Praqmatic-Automated-Changelog/issues/103 before making the final SoW

**Comment by buep** [comment]
I guess this wasn't relevant anymore, so I'm moving it out of Runway and awaiting state.

**Comment by buep** [comment]
I'm closing it - open a new if you need it or work the one in PAC.
