### ISSUE TITLE
Decide on geo location and host for 7th gathering - save the date mail before summer

### ISSUE THREAD

**Issue by buep** [Praqma/josra#42]

**Comment by buep** [comment]
Status ? Closeable? Are you working on a mail to send out?

**Comment by JasmineCrozier** [comment]
Awaiting date confirmation from Samuel.

**Comment by buep** [comment]
I guess that dates are confirmed?

**Comment by JasmineCrozier** [comment]
@buep Yes they are. 
The only things missing are the list of guests from Samuel, and the updated code alliance website.

When can we send the invitation @lakruzz ?
Will one of you have a last look at our list of guests?
https://docs.google.com/spreadsheets/d/1U_VYEuXNf7Qm0WMuQImTRonMrv7mBzKWYGQ7Luv72g0/edit?usp=sharing

**Comment by buep** [comment]
I didn't get why we need the guest list from Samuel? We will invite people -won't we? Or do you mean just his colleagues from Volvo that will join us because we're on their site?

**Comment by buep** [comment]
I'll close this... Jasmine, we will plan more issues on Thursday needed to do the 7th gathering

**Comment by JasmineCrozier** [comment]
Because he has suggested some eiffel experts I think
