### ISSUE TITLE
Plan a demonstration for customer of git-phlow

### ISSUE THREAD

**Issue by buep** [Praqma/josra#51]
Notes from meeting with @drBosse and @groenborg.

Demonstrate it for two groups of not native developers (it-people and analysis/algorithm people).

Focus on communicating that git-phlow makes it simple to use git, and it they agree on our flow git can be really simple and easy and make less training needed to start with.

So the demo need to include context of the Phlow, and then that the git-phlow extension with Windows and Jira support will help.

Pretested integration is a selling point.

Aim for a presentation before summer.
Agenda for the demo meeting:

* slide-deck (with background and context)
* demo - fairly generic
* how can git phlow co-exist with PR workflows and feature branches (also gated by pretested with the phlow)
* questions and customer specific parts

## Goal

Reveal slide-deck with presentation and live demo.
Push for first feedback of stakeholders.

**Comment by groenborg** [comment]
I would like to have more details about how it phlow fits Volvo from @drBosse and some background information about phlow from @buep

**Comment by buep** [comment]
@groenborg  a bit of history to read about our automated phlow and why... http://www.josra.org/blog/An-automated-git-branching-strategy.html

It is a history of why we made our own instead of the git-flow that is also very popular.

And a lot of pros and cons in the discussion.

**Comment by buep** [comment]
Beside that the background I think of is that we made it to simplify working with git and support automation....

**Comment by groenborg** [comment]
@buep Awesome.. I will get right at it!

**Comment by groenborg** [comment]
I will create the slide deck in Praqma/reveals and have created an associated issue Praqma/reveals#43

**Comment by drBosse** [comment]
Talked to Samuel about this last week, just forgot to update, he will check what dates might work for the project. Hope to have more info after this weeks sync meeting on Wednesday

**Comment by buep** [comment]
Moved to backlog... we are not prioritizing it as we're waiting for customer.

**Comment by buep** [comment]
I'm closing this - reopen or create a new one later if needed.
