### ISSUE TITLE
SoW/BluePrint JenkinsAsCode follow-up - publish to customers

### ISSUE THREAD

**Issue by buep** [Praqma/josra#53]

**Comment by buep** [comment]
Status?

**Comment by ewelinawilkosz2** [comment]
I asked couple of people for opinion. I got one from Lars: "I read your document, I love the approach - I'm just anxious to see it run :-)" And I also got some help from Andrey

If you accept it I will save it in Blueprints in our google drive

**Comment by buep** [comment]
Can I get a link to the latest version?

What did Lars mean by that?

**Comment by ewelinawilkosz2** [comment]
I'm hoping to talk with him tomorrow
https://docs.google.com/document/d/12jAbG74jzunkptycb4Tp7NnFVFUgk6LLYhsjpUeGDC8/

**Comment by buep** [comment]
I'll close this - we have new strategy on it's way after tomorrow, and will re-use the same document or create a new one.
