### ISSUE TITLE
MoM 2017-08-24 Bue/Jasmine first planning efforts of 7th gathering

### ISSUE THREAD

**Issue by buep** [Praqma/josra#58]

**Comment by buep** [comment]
@JasmineCrozier 

* We will continue with a spreadsheet like last time - we need to go over it.
* The same spreadsheet will have the agenda in another sheet.
* Practical details like lunch, leaving rooms etc. is going on the agenda.
  * First start 11 AM, but welcome to come 10-11 AM

Save the date mail - waiting on slack rename and minisite update.

Second mail next week, with preliminary elaborate program explained.

Will people come for two days? or only the first day.

**Comment by buep** [comment]
From here on I will groom issues and label them with grey label `alliance7th` so we can track them. Any work in any other repo related to this should be labeled this way.
We will use label, not milestone for progress tracking.

I'll close this when the above is groomed.

**Comment by JasmineCrozier** [comment]
Here is the spreadsheet: https://docs.google.com/spreadsheets/d/1U_VYEuXNf7Qm0WMuQImTRonMrv7mBzKWYGQ7Luv72g0/edit?usp=sharing

**Comment by buep** [comment]
cleaned 3 people... spreadsheet good.

We can make a second batch.

**Comment by buep** [comment]
These issues existed and are relevant:

* https://github.com/Praqma/josra/issues/55
* https://github.com/Praqma/josra/issues/18

I also cleaned a few issues and closes some other.

I'll write new issues.

**Comment by buep** [comment]
I'm closing.

Found also #49 to be relevant.
