### ISSUE TITLE
Change icon on josra.slack.com

### ISSUE THREAD

**Issue by buep** [Praqma/josra#59]
We changed team name on slack, but kept the josra.slack.com url because there was no one better. #57 

But we need a new icon... current one is slack.

**Comment by buep** [comment]
either you fix it Lars og send me an icon when we have it.

**Comment by lakruzz** [comment]
@buep It should pop up here:
https://github.com/Praqma/phablework/issues/79

as soon as JC is done with it!

**Comment by lakruzz** [comment]
<img width="59" alt="alliance square" src="https://user-images.githubusercontent.com/155492/29773795-422004b6-8bff-11e7-8185-e6706597db20.png">

@buep - while we wait - lt's use this one!

**Comment by buep** [comment]
Done, your temporary one uploaded

**Comment by buep** [comment]
seems like this is not going to be done for the next while, so I'll just close this issue and if I get pinged about a new logo I might upload the new one.
