### ISSUE TITLE
Make product catalog description for CC UCM

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/josra#6]
Every product has the following:

- Name
-     Logo (will come)
-     URL
-     Short description
-     Long description
-     Feature list
-     System requirements

Example of one of the products can be seen at https://github.com/Praqma/josra/blob/master/tools/Tracey.md

**Comment by praqma-thi** [comment]
I'll have @MadsNielsen check if the feature list is sound, then I'll just polish it.

**Comment by MadsNielsen** [comment]
Looks good to me. Short and concise.
